version: "3.8"
services:
  pg:
    image: "postgres:alpine"
    container_name: "pos-system-postrges"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5554:5432"
    volumes:
      - "founderhub-data:/var/lib/postgresql/data"
      - ./docker/postgres:/docker-entrypoint-initdb.d
    restart: "always"

volumes:
  founderhub-data:
